### ISSUE TITLE
Separate class files

### ISSUE THREAD

**Issue by dmpresle** [manatarms/Tronh#1]
I was making edits to the classes BEFORE Sacchin split them into separate files. I worked it out and it runs fine on my computer now, but I thought everyone should know this if they haven't pulled the code recently.

**Comment by manatarms** [comment]
Did you push your class to github?

On Thu, Feb 18, 2016 at 7:17 PM, dmpresle < notifications@github.com [notifications@github.com] > wrote:
I was making edits to the classes BEFORE Sacchin split them into separate files.
I worked it out and it runs fine on my computer now, but I thought everyone
should know this if they haven't pulled the code recently.

**Comment by dmpresle** [comment]
I did.
